package com.rite.pillcounting.core.security

import android.util.Base64
import com.rite.pillcounting.core.security.CryptoHelper.encryptField
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Provides AES-GCM-based field-level encryption and decryption using a dual-key
 * (KEK/DEK) architecture.
 *
 * - **KEK (Key Encryption Key):** Derived deterministically from a root secret or Keystore.
 * - **DEK (Data Encryption Key):** Randomly generated per record and wrapped by the KEK.
 * - **AES/GCM/NoPadding:** Ensures authenticated encryption with integrity.
 *
 * Each encrypted payload includes the IV, ciphertext, and wrapped DEK, concatenated with `:`.
 */
object CryptoHelper {

    private const val ALGO = "AES/GCM/NoPadding"
    private const val TAG_LEN = 128
    private val random = SecureRandom()

    /**
     * Derives a deterministic KEK (Key Encryption Key) using SHA-256 hashing of a root secret.
     *
     * @param root The base secret used for deriving the KEK.
     * @return A 256-bit AES key for wrapping DEKs.
     */
    private fun deriveKekKey(root: String): SecretKey {
        val sha = MessageDigest.getInstance("SHA-256").digest(root.toByteArray())
        return SecretKeySpec(sha, "AES")
    }

    private val kek = deriveKekKey("pillcounting-root-secret")

    /** Generates a random 256-bit DEK (Data Encryption Key) for a single field. */
    private fun generateDek(): SecretKey {
        val gen = KeyGenerator.getInstance("AES")
        gen.init(256)
        return gen.generateKey()
    }

    /**
     * Encrypts a field value using AES-GCM with a unique DEK, then wraps the DEK using the KEK.
     *
     * @param plain The plaintext value to encrypt.
     * @return Base64-encoded payload containing IV, ciphertext, and wrapped DEK.
     */
    fun encryptField(plain: String?): String? {
        if (plain.isNullOrBlank()) return plain

        val dek = generateDek()
        val wrappedDek = wrapDek(dek.encoded)
        val iv = ByteArray(12).apply { random.nextBytes(this) }

        val cipher = Cipher.getInstance(ALGO)
        cipher.init(Cipher.ENCRYPT_MODE, dek, GCMParameterSpec(TAG_LEN, iv))
        val ciphertext = cipher.doFinal(plain.toByteArray())

        return buildString {
            append(Base64.encodeToString(iv, Base64.NO_WRAP))
            append(":")
            append(Base64.encodeToString(ciphertext, Base64.NO_WRAP))
            append(":")
            append(Base64.encodeToString(wrappedDek, Base64.NO_WRAP))
        }
    }

    /**
     * Decrypts an encrypted field payload previously generated by [encryptField].
     *
     * @param enc The encoded string containing IV, ciphertext, and wrapped DEK.
     * @return The decrypted plaintext string.
     */
    fun decryptField(enc: String?): String? {
        if (enc.isNullOrBlank()) return enc
        val parts = enc.split(":")
        if (parts.size != 3) return enc

        val iv = Base64.decode(parts[0], Base64.NO_WRAP)
        val ciphertext = Base64.decode(parts[1], Base64.NO_WRAP)
        val wrappedDek = Base64.decode(parts[2], Base64.NO_WRAP)

        val dek = SecretKeySpec(unwrapDek(wrappedDek), "AES")
        val cipher = Cipher.getInstance(ALGO)
        cipher.init(Cipher.DECRYPT_MODE, dek, GCMParameterSpec(TAG_LEN, iv))
        return String(cipher.doFinal(ciphertext))
    }

    /** Encrypts a DEK with the KEK, returning IV-prefixed ciphertext bytes. */
    private fun wrapDek(dekBytes: ByteArray): ByteArray {
        val iv = ByteArray(12).apply { random.nextBytes(this) }
        val cipher = Cipher.getInstance(ALGO)
        cipher.init(Cipher.ENCRYPT_MODE, kek, GCMParameterSpec(TAG_LEN, iv))
        return iv + cipher.doFinal(dekBytes)
    }

    /** Decrypts a wrapped DEK using the KEK, restoring the original DEK bytes. */
    private fun unwrapDek(wrapped: ByteArray): ByteArray {
        val iv = wrapped.copyOfRange(0, 12)
        val enc = wrapped.copyOfRange(12, wrapped.size)
        val cipher = Cipher.getInstance(ALGO)
        cipher.init(Cipher.DECRYPT_MODE, kek, GCMParameterSpec(TAG_LEN, iv))
        return cipher.doFinal(enc)
    }
}
